//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIV_ADMIN1
    {
        public int OBJECTID { get; set; }
        public System.Data.Entity.Spatial.DbGeometry Shape { get; set; }
        public string NOMBRE { get; set; }
        public string DIVADMIN1 { get; set; }
    }
}
