//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Entrevista
    {
        public int ID { get; set; }
        public int IDActivo { get; set; }
        public string Nombre { get; set; }
        public string TipoDoc { get; set; }
        public string Identificacion { get; set; }
        public string Genero { get; set; }
        public string Edo_Civil { get; set; }
        public System.DateTime F_Nacimiento { get; set; }
        public string Idioma { get; set; }
        public string Telefono { get; set; }
        public string Email { get; set; }
        public string TipoProd { get; set; }
        public string Nombre_2 { get; set; }
        public string Telefono_2 { get; set; }
        public string Email_2 { get; set; }
    }
}
