//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sectores
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sectores()
        {
            this.ActivoPre = new HashSet<ActivoPre>();
        }
    
        public int ID { get; set; }
        public int ClaveSector { get; set; }
        public string NomSector { get; set; }
        public Nullable<int> Tipo { get; set; }
        public string AbrevMin { get; set; }
        public string Ministerio { get; set; }
        public int Activo { get; set; }
        public System.DateTime FechaCreado { get; set; }
        public System.DateTime FechaModificado { get; set; }
        public int VersionCat { get; set; }
        public System.DateTime FechaVersionCat { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActivoPre> ActivoPre { get; set; }
    }
}
