//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuarios_View
    {
        public int IDUsuario { get; set; }
        public string NomUsuario { get; set; }
        public string Password { get; set; }
        public string Nombre { get; set; }
        public string Apellidos { get; set; }
        public int IDEvento { get; set; }
        public string Token { get; set; }
        public string Key1 { get; set; }
        public string IV { get; set; }
        public int Sesiones { get; set; }
        public int LimiteSesiones { get; set; }
        public int IDPerfil { get; set; }
        public string Nivel { get; set; }
        public string Descripcion { get; set; }
        public string Tipo { get; set; }
        public System.DateTime FechaCreado { get; set; }
        public System.DateTime FechaModificado { get; set; }
        public Nullable<int> Sector { get; set; }
        public string NomSector { get; set; }
        public System.DateTime FechaExpira { get; set; }
        public int IDProvincia { get; set; }
        public string Correo { get; set; }
        public string Cargo { get; set; }
        public string Telefono { get; set; }
        public string Provincia { get; set; }
    }
}
