//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class VersionCatalog
    {
        public int VersionCatalogos { get; set; }
        public Nullable<System.DateTime> Fecha_Actualizacion { get; set; }
        public string Sectores { get; set; }
    }
}
